title: Jiayi Guo's Homepage
page-top-title: Jiayi Guo
top-section-bg-text: Computer Vision 
home-subtitle: Jiayi Guo&ensp;|&ensp;郭嘉熠
copyright-text: '&copy; Jiayi Guo 2024-2025. All Rights Reserved.'
